// Code generated by easyvalid v0.0.2 . DO NOT EDIT.

package examples

import (
    "errors"
    "github.com/kasiss-liu/easyvalid/_examples/Animal"
)

func (c Cat) EasyValid () (err error) {
    if err = c.valid_8f1f2e730673ef53419e5b787ff3412b798d1085_am(); err != nil {
        return
    }
    if err = c.valid_8f1f2e730673ef53419e5b787ff3412b798d1085_Food(); err != nil {
        return
    }
    return nil
}
func (c Cat) valid_8f1f2e730673ef53419e5b787ff3412b798d1085_am() (err error) {
    if c.am == nil { return errors.New(`am属性不能为空`) }
    return nil
}

func (c Cat) valid_8f1f2e730673ef53419e5b787ff3412b798d1085_Food() (err error) {
    if !(len(c.Food) > 1) { return errors.New(`至少1种食物`) }
    if !(len(c.Food) <= 2) { return errors.New(`最多2种食物`) }
    return nil
}

func (d Dog) EasyValid () (err error) {
    if err = d.valid_62c67d97e5c3380267a9c521eb9911d7209cc130_am(); err != nil {
        return
    }
    if err = d.valid_62c67d97e5c3380267a9c521eb9911d7209cc130_Food(); err != nil {
        return
    }
    if err = d.valid_62c67d97e5c3380267a9c521eb9911d7209cc130_name(); err != nil {
        return
    }
    if err = d.valid_62c67d97e5c3380267a9c521eb9911d7209cc130_Age(); err != nil {
        return
    }
    return nil
}
func (d Dog) valid_62c67d97e5c3380267a9c521eb9911d7209cc130_am() (err error) {
    if d.am == (Animal.Animal{}) { return errors.New(`am属性不能为空`) }
    return nil
}

func (d Dog) valid_62c67d97e5c3380267a9c521eb9911d7209cc130_Food() (err error) {
    if !(len(d.Food) > 1) { return errors.New(`至少1种食物`) }
    if !(len(d.Food) <= 2) { return errors.New(`最多2种食物`) }
    return nil
}

func (d Dog) valid_62c67d97e5c3380267a9c521eb9911d7209cc130_name() (err error) {
    if !(d.name == "xiaogou") { return errors.New(`名称异常`) }
    if d.name == "" { return errors.New(`不能为空`) }
    return nil
}

func (d Dog) valid_62c67d97e5c3380267a9c521eb9911d7209cc130_Age() (err error) {
    if !(d.Age <= 2) { return errors.New(`年龄必须2周岁以上`) }
    return nil
}


